server:
  port: 8799

spring:
  application:
    name: turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  appConfig: user-consumer,user-consumer02
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true