server:
  port: 8763

spring:
  application:
    name: sc-service-rest
  zipkin:
    base-url: http://localhost:8766
    sleuth:
      sampler:
        percentage: 1.0 #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大

    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        # 开启指定端点
        include: 'hystrix.stream'

feign:
  hystrix:
    enabled: true