server:
  port: 8789

spring:
  application:
    name: user-consumer02

  zipkin:
    sender:
      type: web
    base-url: http://localhost:8766
    sleuth:
      sampler:
        percentage: 1.0 #0.1-1.0 也就是代表链路跟踪的数据上传的概率有多大

    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#开启feign熔断
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # 开启指定端点
        include: 'hystrix.stream'

